// ============ DUMMY EVENTS DATA ============

const DUMMY_EVENTS = [
    // Dance Events
    {
        id: "EVENT001",
        name: "Bollywood Dance Night",
        category: "Dance",
        date: "2026-05-15",
        time: "19:00",
        venue: "Grand Theater, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 500,
        seats: 200,
        available: 45,
        image: "🎭",
        description: "Experience vibrant Bollywood dance performances with live music",
        rating: 4.5,
        type: "dance"
    },
    {
        id: "EVENT002",
        name: "Contemporary Dance Festival",
        category: "Dance",
        date: "2026-05-18",
        time: "18:30",
        venue: "Arts Complex, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 600,
        seats: 150,
        available: 30,
        image: "🎭",
        description: "Modern and contemporary dance performances by renowned artists",
        rating: 4.3,
        type: "dance"
    },
    {
        id: "EVENT003",
        name: "Classical Dance Recital",
        category: "Dance",
        date: "2026-05-20",
        time: "19:00",
        venue: "Cultural Center, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 700,
        seats: 180,
        available: 60,
        image: "🎭",
        description: "Traditional Kathak, Bharatanatyam, and Odissi dance performances",
        rating: 4.6,
        type: "dance"
    },
    {
        id: "EVENT004",
        name: "Street Jazz Dance Battle",
        category: "Dance",
        date: "2026-05-22",
        time: "20:00",
        venue: "Open Auditorium, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 400,
        seats: 250,
        available: 80,
        image: "🎭",
        description: "High-energy hip-hop and street dance battle",
        rating: 4.2,
        type: "dance"
    },

    // Singing Events
    {
        id: "EVENT005",
        name: "Unplugged Music Night",
        category: "Singing",
        date: "2026-05-16",
        time: "19:00",
        venue: "Auditorium, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 450,
        seats: 300,
        available: 75,
        image: "🎤",
        description: "Acoustic performances by popular singers",
        rating: 4.4,
        type: "singing"
    },
    {
        id: "EVENT006",
        name: "Classical Vocal Concert",
        category: "Singing",
        date: "2026-05-19",
        time: "18:00",
        venue: "Heritage Hall, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 800,
        seats: 200,
        available: 40,
        image: "🎤",
        description: "Mesmerizing classical Indian vocal performances",
        rating: 4.7,
        type: "singing"
    },
    {
        id: "EVENT007",
        name: "Indie Music Festival",
        category: "Singing",
        date: "2026-05-21",
        time: "19:30",
        venue: "Open Auditorium, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 550,
        seats: 400,
        available: 120,
        image: "🎤",
        description: "Independent and alternative music artists showcase",
        rating: 4.3,
        type: "singing"
    },
    {
        id: "EVENT008",
        name: "Pop Concert Extravaganza",
        category: "Singing",
        date: "2026-05-23",
        time: "19:00",
        venue: "Convention Hall, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 1200,
        seats: 500,
        available: 150,
        image: "🎤",
        description: "Top pop artists live performances",
        rating: 4.6,
        type: "singing"
    },

    // Cultural Events
    {
        id: "EVENT009",
        name: "Cultural Heritage Festival",
        category: "Cultural",
        date: "2026-05-17",
        time: "10:00",
        venue: "Open Auditorium, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 300,
        seats: 500,
        available: 200,
        image: "🏛️",
        description: "Celebrate diverse Indian cultural traditions and crafts",
        rating: 4.5,
        type: "cultural"
    },
    {
        id: "EVENT010",
        name: "Folk Music & Dance Fusion",
        category: "Cultural",
        date: "2026-05-20",
        time: "17:00",
        venue: "Cultural Center, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 400,
        seats: 350,
        available: 90,
        image: "🏛️",
        description: "Traditional folk performances from different regions",
        rating: 4.4,
        type: "cultural"
    },
    {
        id: "EVENT011",
        name: "Art Exhibition & Cultural Talk",
        category: "Cultural",
        date: "2026-05-24",
        time: "14:00",
        venue: "Convention Hall, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 250,
        seats: 200,
        available: 60,
        image: "🏛️",
        description: "Contemporary and traditional art exhibition",
        rating: 4.3,
        type: "cultural"
    },
    {
        id: "EVENT012",
        name: "Traditional Craft Workshop",
        category: "Cultural",
        date: "2026-05-25",
        time: "15:00",
        venue: "Open Auditorium, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 500,
        seats: 100,
        available: 35,
        image: "🏛️",
        description: "Learn traditional Indian crafts and techniques",
        rating: 4.2,
        type: "cultural"
    },

    // Reality Shows
    {
        id: "EVENT013",
        name: "Singing Reality Show Auditions",
        category: "Reality Show",
        date: "2026-05-18",
        time: "10:00",
        venue: "Convention Hall, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 200,
        seats: 1000,
        available: 450,
        image: "📺",
        description: "Be part of live auditions for popular singing reality show",
        rating: 4.1,
        type: "reality"
    },
    {
        id: "EVENT014",
        name: "Dance Competition - Live Taping",
        category: "Reality Show",
        date: "2026-05-21",
        time: "14:00",
        venue: "Open Auditorium, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 300,
        seats: 800,
        available: 300,
        image: "📺",
        description: "Watch live recording of dance reality competition",
        rating: 4.2,
        type: "reality"
    },
    {
        id: "EVENT015",
        name: "Comedy Reality Show Live Taping",
        category: "Reality Show",
        date: "2026-05-23",
        time: "18:00",
        venue: "Grand Theater, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 400,
        seats: 600,
        available: 180,
        image: "📺",
        description: "Experience comedy reality show filming with live audience",
        rating: 4.3,
        type: "reality"
    },
    {
        id: "EVENT016",
        name: "Talent Hunt - Auditions",
        category: "Reality Show",
        date: "2026-05-26",
        time: "11:00",
        venue: "Convention Hall, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 250,
        seats: 900,
        available: 400,
        image: "📺",
        description: "Multi-talent auditions for new reality show",
        rating: 4.0,
        type: "reality"
    },

    // Stand-up Comedy
    {
        id: "EVENT017",
        name: "Comedy Night - Local Comics",
        category: "Stand-up Comedy",
        date: "2026-05-16",
        time: "20:00",
        venue: "Comedy Club, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 350,
        seats: 250,
        available: 60,
        image: "🎭",
        description: "Hilarious stand-up performances by emerging comedians",
        rating: 4.4,
        type: "comedy"
    },
    {
        id: "EVENT018",
        name: "Stand-up Comedy Fest 2026",
        category: "Stand-up Comedy",
        date: "2026-05-19",
        time: "19:00",
        venue: "Grand Theater, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 600,
        seats: 400,
        available: 100,
        image: "🎭",
        description: "Comedy festival featuring top stand-up comedians",
        rating: 4.5,
        type: "comedy"
    },
    {
        id: "EVENT019",
        name: "Celebrity Comedy Show",
        category: "Stand-up Comedy",
        date: "2026-05-22",
        time: "19:00",
        venue: "Convention Hall, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 800,
        seats: 700,
        available: 200,
        image: "🎭",
        description: "Special performance by famous international comedian",
        rating: 4.6,
        type: "comedy"
    },
    {
        id: "EVENT020",
        name: "Comedy Jam Night",
        category: "Stand-up Comedy",
        date: "2026-05-24",
        time: "20:00",
        venue: "Open Auditorium, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 400,
        seats: 500,
        available: 150,
        image: "🎭",
        description: "Multi-comedian jam session with interactive segments",
        rating: 4.3,
        type: "comedy"
    },

    // Functional Halls Bookings
    {
        id: "HALL001",
        name: "Corporate Conference Hall - 500 Capacity",
        category: "Functional Hall",
        date: "2026-05-20",
        time: "09:00",
        venue: "Tech Park, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 5000,
        seats: 500,
        available: 1,
        image: "🏢",
        description: "Modern conference hall with AV equipment and WiFi",
        rating: 4.4,
        type: "functional_hall",
        amenities: ["Projector", "Sound System", "WiFi", "AC", "Parking"]
    },
    {
        id: "HALL002",
        name: "Event Space - 300 Capacity",
        category: "Functional Hall",
        date: "2026-05-21",
        time: "10:00",
        venue: "Downtown, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 3500,
        seats: 300,
        available: 1,
        image: "🏢",
        description: "Versatile event space for corporate and private events",
        rating: 4.3,
        type: "functional_hall",
        amenities: ["Lighting", "Sound System", "WiFi", "Catering", "Parking"]
    },
    {
        id: "HALL003",
        name: "Seminar Hall - 200 Capacity",
        category: "Functional Hall",
        date: "2026-05-22",
        time: "14:00",
        venue: "Business Hub, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 2500,
        seats: 200,
        available: 1,
        image: "🏢",
        description: "Professional seminar hall with modern amenities",
        rating: 4.2,
        type: "functional_hall",
        amenities: ["Projector", "WiFi", "AC", "Parking", "Lounge"]
    },
    {
        id: "HALL004",
        name: "Training Center - 150 Capacity",
        category: "Functional Hall",
        date: "2026-05-23",
        time: "09:00",
        venue: "Convention District, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 2000,
        seats: 150,
        available: 1,
        image: "🏢",
        description: "Equipped training center with breakout rooms",
        rating: 4.1,
        type: "functional_hall",
        amenities: ["Breakout Rooms", "WiFi", "AC", "Projector", "Parking"]
    },

    // Conventional Halls
    {
        id: "CONV001",
        name: "Banquet Hall - Royal Palace",
        category: "Conventional Hall",
        date: "2026-05-25",
        time: "18:00",
        venue: "Heritage District, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 8000,
        seats: 400,
        available: 1,
        image: "💍",
        description: "Luxurious banquet hall for weddings and celebrations",
        rating: 4.6,
        type: "conventional_hall",
        amenities: ["Catering", "Decoration", "Sound System", "Parking", "AC"]
    },
    {
        id: "CONV002",
        name: "Grand Wedding Hall",
        category: "Conventional Hall",
        date: "2026-05-26",
        time: "17:00",
        venue: "Celebration Center, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 10000,
        seats: 600,
        available: 1,
        image: "💍",
        description: "Premium wedding hall with complete catering services",
        rating: 4.7,
        type: "conventional_hall",
        amenities: ["Catering", "Decoration", "Photography", "Valet", "AC"]
    },
    {
        id: "CONV003",
        name: "Celebration Palace",
        category: "Conventional Hall",
        date: "2026-05-27",
        time: "16:00",
        venue: "Event Zone, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 12000,
        seats: 800,
        available: 1,
        image: "💍",
        description: "Elegantly designed hall for all types of celebrations",
        rating: 4.8,
        type: "conventional_hall",
        amenities: ["Catering", "Decoration", "Photography", "Videography", "Parking"]
    },
    {
        id: "CONV004",
        name: "Royal Banquet Heritage",
        category: "Conventional Hall",
        date: "2026-05-28",
        time: "18:00",
        venue: "Prestige District, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 9000,
        seats: 500,
        available: 1,
        image: "💍",
        description: "Traditional banquet with modern amenities",
        rating: 4.5,
        type: "conventional_hall",
        amenities: ["Catering", "Decoration", "Sound System", "Parking", "Kitchen"]
    },

    // Meeting Halls
    {
        id: "MEET001",
        name: "Executive Boardroom - Small Meeting",
        category: "Meeting Hall",
        date: "2026-05-20",
        time: "10:00",
        venue: "Business Complex, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 1000,
        seats: 20,
        available: 1,
        image: "📊",
        description: "Intimate boardroom for executive meetings",
        rating: 4.3,
        type: "meeting_hall",
        amenities: ["WiFi", "Projector", "Phone System", "AC", "Refreshments"]
    },
    {
        id: "MEET002",
        name: "Corporate Meeting Suite - Medium",
        category: "Meeting Hall",
        date: "2026-05-21",
        time: "14:00",
        venue: "Corporate Park, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 2000,
        seats: 50,
        available: 1,
        image: "📊",
        description: "Professional meeting suite with breakout areas",
        rating: 4.4,
        type: "meeting_hall",
        amenities: ["WiFi", "Projector", "Video Conference", "AC", "Parking"]
    },
    {
        id: "MEET003",
        name: "Convention Meeting Center - Large",
        category: "Meeting Hall",
        date: "2026-05-22",
        time: "10:00",
        venue: "Convention Hub, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 3500,
        seats: 100,
        available: 1,
        image: "📊",
        description: "Large convention meeting hall with multiple breakout rooms",
        rating: 4.5,
        type: "meeting_hall",
        amenities: ["WiFi", "Video Conference", "Breakout Rooms", "Catering", "Parking"]
    },
    {
        id: "MEET004",
        name: "Premium Business Meeting Hall",
        category: "Meeting Hall",
        date: "2026-05-23",
        time: "11:00",
        venue: "Business Square, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 2500,
        seats: 75,
        available: 1,
        image: "📊",
        description: "State-of-the-art meeting facility with tech support",
        rating: 4.6,
        type: "meeting_hall",
        amenities: ["WiFi", "Video Conference", "Tech Support", "Catering", "Parking"]
    },

    // Open Auditorium Events
    {
        id: "AUD001",
        name: "Open Air Music Festival",
        category: "Open Auditorium",
        date: "2026-05-30",
        time: "17:00",
        venue: "Central Park Amphitheater, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 300,
        seats: 2000,
        available: 600,
        image: "🎪",
        description: "Multi-genre music festival in open air",
        rating: 4.4,
        type: "open_auditorium"
    },
    {
        id: "AUD002",
        name: "Outdoor Theater Festival",
        category: "Open Auditorium",
        date: "2026-06-02",
        time: "19:00",
        venue: "Riverside Amphitheater, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 250,
        seats: 1500,
        available: 500,
        image: "🎪",
        description: "Classical and contemporary theater performances under stars",
        rating: 4.3,
        type: "open_auditorium"
    },
    {
        id: "AUD003",
        name: "Summer Arts Festival - Open Venue",
        category: "Open Auditorium",
        date: "2026-06-05",
        time: "18:00",
        venue: "Beach Amphitheater, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 400,
        seats: 2500,
        available: 800,
        image: "🎪",
        description: "Celebrate arts with music, dance, and performances",
        rating: 4.5,
        type: "open_auditorium"
    },
    {
        id: "AUD004",
        name: "Community Cultural Gathering",
        category: "Open Auditorium",
        date: "2026-06-08",
        time: "17:00",
        venue: "Central Grounds, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 200,
        seats: 3000,
        available: 1000,
        image: "🎪",
        description: "Free and open community cultural event for all",
        rating: 4.2,
        type: "open_auditorium"
    },
    {
        id: "EVENT021",
        name: "Tech Creator Meetup",
        category: "Cultural",
        date: "2026-06-10",
        time: "16:00",
        venue: "Innovation Hub, Hyderabad",
        location: "Hyderabad",
        city: "Hyderabad",
        price: 350,
        seats: 450,
        available: 160,
        image: "💡",
        description: "A creator meetup with talks, networking and live showcases.",
        rating: 4.4,
        type: "cultural"
    },
    {
        id: "EVENT022",
        name: "Indie Film Fan Fest",
        category: "Reality Show",
        date: "2026-06-12",
        time: "18:30",
        venue: "City Auditorium, Bangalore",
        location: "Bangalore",
        city: "Bangalore",
        price: 500,
        seats: 600,
        available: 220,
        image: "🎬",
        description: "Interactive fan fest with creators, cast discussions and games.",
        rating: 4.5,
        type: "reality"
    },
    {
        id: "EVENT023",
        name: "Night Laugh Arena",
        category: "Stand-up Comedy",
        date: "2026-06-14",
        time: "20:00",
        venue: "Laugh House, Mumbai",
        location: "Mumbai",
        city: "Mumbai",
        price: 650,
        seats: 380,
        available: 140,
        image: "😄",
        description: "Premium stand-up night featuring multiple headline comedians.",
        rating: 4.6,
        type: "comedy"
    },
    {
        id: "EVENT024",
        name: "Fusion Street Beats",
        category: "Dance",
        date: "2026-06-16",
        time: "19:00",
        venue: "Riverfront Arena, Delhi",
        location: "Delhi",
        city: "Delhi",
        price: 420,
        seats: 700,
        available: 290,
        image: "🕺",
        description: "Street and fusion dance championship with team battles.",
        rating: 4.3,
        type: "dance"
    }
];

// Get events by category
function getEventsByCategory(category) {
    return DUMMY_EVENTS.filter(event => event.category === category);
}

// Get events by city/location
function getEventsByLocation(location) {
    return DUMMY_EVENTS.filter(event => event.location === location);
}

// Get all unique event categories
function getEventCategories() {
    const categories = [...new Set(DUMMY_EVENTS.map(e => e.category))];
    return categories;
}

// Get all unique locations
function getEventLocations() {
    const locations = [...new Set(DUMMY_EVENTS.map(e => e.location))];
    return locations.sort();
}

// Search events
function searchEvents(query, location = '') {
    let results = DUMMY_EVENTS.filter(event => 
        event.name.toLowerCase().includes(query.toLowerCase()) ||
        event.category.toLowerCase().includes(query.toLowerCase()) ||
        event.description.toLowerCase().includes(query.toLowerCase())
    );
    
    if (location) {
        results = results.filter(event => event.location === location);
    }
    
    return results;
}


